import Link from "next/link";

export default function Homepage() {
  return (
    <div>
      <Link href="/auth/signin">To Sign In</Link>
      <h1>Welcome to Create Next App!</h1>
      <p>Generated by create next app</p>
    </div>
  );
}
