"use server";

export default async function Homepage(): Promise<JSX.Element> {
  return (
    <div className="flex flex-col justify-center items-center space-y-5">
      <p>Generated by create-next-app</p>
    </div>
  );
}
