"use server";

export default async function Homepage(): Promise<JSX.Element> {
  return (
    <div className="flex flex-col justify-center items-center space-y-5">
      <p>Generated by create-next-app</p>
      <label className="flex cursor-pointer gap-2">
        <span className="label-text">Toggle Theme</span>
        <input
          className="toggle theme-controller"
          type="checkbox"
          value="light"
        />
      </label>
    </div>
  );
}
